config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

resources :contacts

resources :drivers
resources :trucks
resources :trailers
resources :loads
resources :shippers

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_presence_of :name, :pass, :username
	validates_uniqueness_of :username
end

app/models/driver.rb
class Driver < ActiveRecord::Base
	validates_presence_of :fname, :lname, :licnum, :dob

	belongs_to :truck

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/models/load.rb
class Load < ActiveRecord::Base
	validates_presence_of :length, :width, :height, :weight, :nickname, :shipper_id

	belongs_to :trailer
	belongs_to :shipper

end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
	validates_presence_of :name

	has_many :loads

end

app/models/testenv.rb
class Testenv < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	validates_presence_of :licnum, :length, :width, :height

	belongs_to :truck
	has_many :loads

	def select_label
		if self.nickname != (nil or '')
			return "#{self.licnum} (#{self.nickname})"
		else
			return "#{self.licnum}"
		end
	end

end

app/models/truck.rb
class Truck < ActiveRecord::Base
	validates_presence_of :licnum

	has_many :drivers
	has_one :trailer
	accepts_nested_attributes_for :trailer

	def select_label
		if self.nickname != (nil or '')
			return "#{self.licnum} (#{self.nickname})"
		else
			return "#{self.licnum}"
		end
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :get_contact, only: [:edit, :update, :destroy]

  def get_contact
    @contact = Contact.find(params[:id])
  end

  def index
    @title = "All Contacts"
    @contact = Contact.all.order(:username)
  end

  def show
    @contact = Contact.find(params[:id])
    respond_to do |f|
      f.html
      f.json { render json: @contact}
    end
  end

  def new
    @contact = Contact.new
  end

  def edit
    
  end

  def create
    @contact = Contact.new(contact_params)
    #@contact.request = request
    if @contact.save
      redirect_to(contacts_path, notice: 'User was created successfully')
    else
      redirect_to(contacts_path, alert: 'Cannot create user.')
    end
  end

  def update

  end

  def destroy
    @contact.destroy
    redirect_to(contacts_path, notice: "User was deleted successfully")
  end

  

  private
  ## Strong Parameters 
  def contact_params
    params.require(:contact).permit(:name, :pass, :username)
  end

end


=begin
class UsersController < ApplicationController
  ## ...
  def create
    @user = User.new(user_params) ## Invoke user_params method
    if @user.save
      redirect_to @user, notice: 'User was successfully created.' 
    else
      render action: 'new'
    end       
  end
  ## ... 

end 

=end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]

  def get_item
    @driver = Driver.find(params[:id])
  end

  def index
    @title = 'All Drivers'
    @driver = Driver.all.order(:lname)
  end

  def show
    @driver = Driver.find(params[:id])
    @title = @driver.fname + ' ' + @driver.lname
    respond_to do |f|
      f.html
      f.json { render json: @driver}
    end
  end

  def edit
  	@title = 'Edit Driver'
  	session[:return_to] = request.referer
  end

  def new
  	@title = 'Create Driver'
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)

    if @driver.save
      redirect_to(drivers_path, notice: 'Driver was created successfully')
    else
      redirect_to(drivers_path, alert: 'Cannot create driver.')
    end
  end

  def update
  	@driver = Driver.update(@driver.id, driver_params)

    if @driver.save
    	redirect_to(session.delete(:return_to), notice: 'Driver was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(drivers_path, alert: 'Cannot update driver.')
    end
  end

  def destroy
    @driver.destroy
    redirect_to(drivers_path, notice: 'Driver was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def driver_params
    params.require(:driver).permit(:fname, :lname, :licnum, :dob, :truck_id)
  end

end

app/controllers/input_controller.rb
class InputController < ApplicationController
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]


  def get_item
    @load = Load.find(params[:id])
  end

  def index
    @title = 'All Loads'
    @load = Load.all.order(:nickname)
  end

  def show
    @load = Load.find(params[:id])
    @title = @load.nickname
    respond_to do |f|
      f.html
      f.json { render json: @load}
    end
  end

  def edit
    @title = "Edit Load"
    session[:return_to] = request.referer
  end

  def new
    @title = "New Load"
    @load = Load.new
  end

  def create
    @load = Load.new(load_params)

    if @load.save
      redirect_to(loads_path, notice: 'Load was created successfully')
    else
      redirect_to(loads_path, alert: 'Cannot create load.')
    end
  end

  def update
    @load = Load.update(@load.id, load_params)

    if @load.save
      redirect_to(session.delete(:return_to), notice: 'Load was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(loads_path, alert: 'Cannot update load.')
    end
  end

  def destroy
    @load.destroy
    redirect_to(loads_path, notice: 'Load was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def load_params
    params.require(:load).permit(:nickname, :length, :width, :height, :weight, :trailer_id, :shipper_id)
  end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]

  def get_item
    @truck = Truck.find(params[:id])
  end

  def index
    @title = 'All Trucks'
    @truck = Truck.all.order(:nickname)
  end

  def show
    @truck = Truck.find(params[:id])
    if @truck.nickname != (nil or '')
      @title = @truck.licnum + ' (' + @truck.nickname+')'
    else
      @title = @truck.licnum
    end
    respond_to do |f|
      f.html
      f.json { render json: @truck}
    end
  end

  def edit
    @title = "Edit Truck"
    session[:return_to] = request.referer
  end

  def new
    @title = "New Truck"
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)
    trailer = Trailer.find(params[:truck][:trailer_id])
    @truck.trailer = trailer
    if @truck.save
      redirect_to(trucks_path, notice: 'Truck was created successfully')
    else
      redirect_to(trucks_path, alert: 'Cannot create truck.')
    end
  end

  def update
    @truck = Truck.update(@truck.id, truck_params)

    trailer = Trailer.find(params[:truck][:trailer_id])
    @truck.trailer = trailer
    if @truck.save
      redirect_to(session.delete(:return_to), notice: 'Truck was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(trucks_path, alert: 'Cannot update truck.')
    end
  end

  def destroy
    @truck.destroy
    redirect_to(trucks_path, notice: 'Truck was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def truck_params
    params.require(:truck).permit(:nickname, :licnum, :trailer_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/helpers/load_helper.rb
module LoadHelper
end

app/helpers/shipper_helper.rb
module ShipperHelper
end

app/helpers/trailer_helper.rb
module TrailerHelper
end

app/helpers/truck_helper.rb
module TruckHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<% content_for :title do %>
All Contacts
<% end %>
	<h2>All Contacts</h2>
		<table>
			<thead>
			<tr>
				<th>Username</th>
				<th>Name</th>
				<th>Changes</th>
			</tr>
			</thead>
			
			<tbody>
			<% @contact.each do |c| %>
			
			<tr>
				<td><%= link_to c.username, c %></td>
				<td><%= c.name%></td>
				<td><%= link_to "Edit", edit_contact_path(c), class: 'button small' %>    <%= link_to "Delete", c, method: :delete, class: 'button small'  %></td>
			</tr>
			
			<%end%>
			</tbody>
			

		</table>
		
		<% if @contact.size == 0 %>
				<em>No Contacts Found</em>
		<%end%>

	</div>

app/views/contacts/new.html.erb
	<h2>Create New Contact</h2>
	

	<div class = 'large-4 columns'>
	<%= simple_form_for @contact do |f| %>
		
	  	<%= f.input :name%>
	  	<%= f.input :username%>
		<%= f.input :pass, label: 'Password' %>
	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/contacts/show.html.erb
<h2><%=@contact.name%></h2>

<table>
	<thead>
		<tr>
			<th>Username</th>
			<th>Password</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
			<td><%=@contact.username%></td>	
			<td><%=@contact.pass%></td>
		</tr>	
	</tbody>
	

</table>

app/views/drivers/edit.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>

	<div class = 'large-6 columns'>
	<%= simple_form_for @driver do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :fname, label: 'First Name'%>
	  	<%= f.input :lname, label: 'Last Name'%>
			
			<%= f.input :dob, as: :string, label: 'Date of Birth'%>

			<%= f.association :truck, label_method: :select_label%>
	  	

	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/drivers/index.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>
		<table>
			<thead>
			<tr>
				
				<th>License #</th>
				<th>First Name</th>
				<th>Last Name</th>
				
				<th>DOB</th>
				<th>Truck</th>
				<th>Modify</th>
			</tr>
			</thead>
			
			<tbody>
			<% @driver.each do |c| %>
			
			<tr>
				<td><%= link_to c.licnum, c%></td>
				<td><%= c.fname%></td>
				<td><%= c.lname%></td>
				
				<td><%= c.dob%></td>
				<td>
						<% if c.truck != nil %>
							<%=link_to c.truck.licnum, truck_path(c.truck_id)%> 
							<% if c.truck.nickname != (nil or '') %>
								(<%= c.truck.nickname%>)
								<%else%>
									<%= '' %>
						<%end%>
						<%else%>
							<%= 'Not Assigned' %>
						<%end%>
							
				</td>
				<td>
						<%= link_to "Edit", edit_driver_path(c), class: 'button small' %>
						<%= link_to "Delete", c, method: :delete, class: 'button small'  %>
				</td>
			</tr>
			
			<%end%>
			</tbody>
			

		</table>
		
		<% if @driver.size == 0 %>
				<em>No Drivers Found</em><br /><br />
		<%end%>

		<a href="/drivers/new" class="button small">New Driver</a>

	</div>

app/views/drivers/new.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @driver do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :fname, label: 'First Name'%>
	  	<%= f.input :lname, label: 'Last Name'%>
			
			<%= f.input :dob, as: :string, label: 'Date of Birth'%>
			<%= f.association :truck, label_method: :select_label%>
	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/drivers/show.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>


<table>
	<thead>
		<tr>
			<th>License #</th>
			<th>First Name</th>
			<th>Last Name</th>
			
			<th>DOB</th>
			<th>Truck</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
		<td><%= @driver.licnum%></td>
			<td><%=@driver.fname%></td>
				<td><%= @driver.lname%></td>
				
				<td><%= @driver.dob%></td>
				<td>
						<% if @driver.truck != nil %>
							<%= link_to @driver.truck.licnum, truck_path(@driver.truck_id)%>
							<% if @driver.truck.nickname != (nil or '') %>
								(<%= @driver.truck.nickname%>)
								<%else%>
									<%= '' %>
						<%end%>
						<%else%>
							<%= link_to 'Assign', edit_driver_path %>
						<%end%>
							
				</td>
		</tr>	
	</tbody>
	


</table>

<%= link_to "Edit Driver", edit_driver_path(@driver), class: 'button small' %>
<a href="/drivers" class="button small">All Drivers</a>

app/views/input/input.html.erb
<h2> Input Items </h2>


<% test = "test." %>
This is a <%= test %>


<%= simple_form_for @input do |f| %>
  <%= f.input :name %>
  <%= f.input :pass %>
  <%= f.button :submit %>
<% end %>

app/views/loads/edit.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @load do |f| %>
			<%= f.input :nickname, label: 'Nickname'%>
	  	
	  	<%= f.input :length, label: 'Length' %>
	  	<%= f.input :width, label: 'Width' %>
	  	<%= f.input :height, label: 'Height' %>
	  	<%= f.input :weight, label: 'Weight' %>

	  	<%= f.association :trailer, label_method: :select_label%>
	  	<%= f.association :shipper%>
			
	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/loads/index.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>
		<table>
			<thead>
			<tr>
				<th>Nickname</th>
				<th>Dimensions (LxWxH)</th>
				<th>Weight</th>
				<th>Trailer</th>
				<th>Shipper</th>
				<th>Modify</th>
			</tr>
			</thead>
			
			<tbody>
			<% @load.each do |c| %>
			
			<tr>
				<td><%= link_to c.nickname, c%></td>
				<td><%=c.length%> x <%=c.width%> x <%=c.height%></td>
				<td><%=c.weight%></td>
				<td>
				<% if c.trailer != nil %>
						<%if c.trailer.nickname != (nil or '')%>
      				<%=link_to c.trailer.licnum, trailer_path(c.trailer)%>  <%=' (' + c.trailer.nickname+')'%>
    				<%else%>
      				<%=link_to c.trailer.licnum, trailer_path(c.trailer)%>
    				<%end%>
				<%else%>
						<%= 'No Trailer' %>
				<%end%>
				</td>
				<td>
					<% if c.shipper != nil %>
      				<%=link_to c.shipper.name, shipper_path(c.shipper)%>
					<%else%>
						<%= 'No Shipper' %>
					<%end%>
				</td>
				</td>
				<td>
						<%= link_to "Edit", edit_load_path(c), class: 'button small' %>
						<%= link_to "Delete", c, method: :delete, class: 'button small'  %>
				</td>
			</tr>
			
			<%end%>
			</tbody>
			

		</table>
		
		<% if @load.size == 0 %>
				<em>No Loads Found</em><br /><br />
		<%end%>

		<a href="/loads/new" class="button small">New Load</a>

	</div>

app/views/loads/new.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @load do |f| %>
			<%= f.input :nickname, label: 'Nickname'%>
	  	
	  	<%= f.input :length, label: 'Length' %>
	  	<%= f.input :width, label: 'Width' %>
	  	<%= f.input :height, label: 'Height' %>
	  	<%= f.input :weight, label: 'Weight' %>

	  	<%= f.association :trailer, label_method: :select_label%>
	  	<%= f.association :shipper%>
			
	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/loads/show.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

<h2><%=@title%></h2>

<table>
	<thead>
		<tr>
				<th>Nickname</th>
				<th>Dimensions (LxWxH)</th>
				<th>Weight</th>
				<th>Trailer</th>
				<th>Shipper</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
		<td><%= @load.nickname%></td>
		<td><%=@load.length%> x <%=@load.width%> x <%=@load.height%></td>
		<td><%=@load.weight%></td>
		<td>
			<% if @load.trailer != nil %>
						<%if @load.trailer.nickname != (nil or '')%>
      				<%=link_to @load.trailer.licnum, trailer_path(@load.trailer)%>  <%=' (' + @load.trailer.nickname+')'%>
    				<%else%>
      				<%=link_to @load.trailer.licnum, trailer_path(@load.trailer)%>
    				<%end%>
				<%else%>
						<%= 'No Trailer' %>
				<%end%>
		</td>
		<td>
					<% if @load.shipper != nil %>
      				<%=link_to @load.shipper.name, shipper_path(@load.shipper)%>
					<%else%>
						<%= 'No Shipper' %>
					<%end%>
				</td>
		
		</tr>	
	</tbody>
	


</table>
<%= link_to "Edit Load", edit_load_path(@load), class: 'button small' %>
<a href="/loads" class="button small">All Loads</a>

app/views/trucks/edit.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @truck do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :nickname, label: 'Nickname', placeholder: 'Optional'%>
			<%= f.input :trailer_id,:collection => Trailer.all,:label_method => :select_label,:value_method => :id,:label => "Trailer" %>
			<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/trucks/index.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>
		<table>
			<thead>
			<tr>
				
				<th>License #</th>
				<th>Nickname</th>
				<th>Drivers</th>
				<th>Trailer</th>
				<th>Modify</th>
			</tr>
			</thead>
			
			<tbody>
			<% @truck.each do |c| %>
			
			<tr>
				<td><%= link_to c.licnum, c%></td>
				<td>
				<% if c.nickname != (nil or '') %>
						<%= c.nickname%>
				<%else%>
					<%= 'No Nickname' %>
				<%end%>
				</td>
				<td>
				<% if c.drivers != [] %>
						<% c.drivers.each do |t|%>
								<%= link_to t.fname, driver_path(t)%><br />
						<%end%>
				<%else%>
						<%= 'No Drivers' %>
				<%end%>
				</td>
				<td>
					<% if c.trailer != nil %>
						<%if c.trailer.nickname != (nil or '')%>
      				<%=link_to c.trailer.licnum, trailer_path(c.trailer)%>  <%=' (' + c.trailer.nickname+')'%>
    				<%else%>
      				<%=link_to c.trailer.licnum, trailer_path(c.trailer)%>
    				<%end%>
					<%else%>
						<%= 'No Trailer' %>
					<%end%>
				</td>
				<td>
						<%= link_to "Edit", edit_truck_path(c), class: 'button small' %>
						<%= link_to "Delete", c, method: :delete, class: 'button small'  %>
				</td>
			</tr>
			
			<%end%>
			</tbody>
			

		</table>
		
		<% if @truck.size == 0 %>
				<em>No Trucks Found</em><br /><br />
		<%end%>

		<a href="/trucks/new" class="button small">New Truck</a>

	</div>

app/views/trucks/new.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @truck do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :nickname, label: 'Nickname', placeholder: 'Optional'%>
			<%= f.input :trailer_id,:collection => Trailer.all,:label_method => :select_label,:value_method => :id,:label => "Trailer" %>
			<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/trucks/show.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

<h2><%=@title%></h2>

<table>
	<thead>
		<tr>
			<th>License #</th>
				<th>Nickname</th>
				<th>Drivers</th>
				<th>Trailer</th>
		</tr>
	</thead>
	
	<tbody>
		<tr>
		<td><%=@truck.licnum%></td>
				<td><% if @truck.nickname != (nil or '') %>
						<%= @truck.nickname%>
				<%else%>
					<%= 'No Nickname' %>
				<%end%></td>
				<td>
						<% if @truck.drivers != [] %>
							<% @truck.drivers.each do |t|%>
								<%= link_to t.fname, driver_path(t)%>
							<%end%>
						<%else%>
							<%= 'No Drivers' %>
						<%end%>
				</td>
				
				<td>
					<% if @truck.trailer != nil %>
						<%if @truck.trailer.nickname != (nil or '')%>
      				<%=link_to @truck.trailer.licnum, trailer_path(@truck.trailer)%>  <%=' (' + @truck.trailer.nickname+')'%>
    				<%else%>
      				<%=link_to @truck.trailer.licnum, trailer_path(@truck.trailer)%>
    				<%end%>
					<%else%>
						<%= 'No Trailer' %>
					<%end%>
				</td>
		</tr>	
	</tbody>
	


</table>
<%= link_to "Edit Truck", edit_truck_path(@truck), class: 'button small' %>
<a href="/trucks" class="button small">All Trucks</a>