config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

resources :contacts

resources :drivers
resources :trucks
resources :trailers
resources :loads
resources :shippers

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_presence_of :name, :pass, :username
	validates_uniqueness_of :username
end

app/models/driver.rb
class Driver < ActiveRecord::Base
	validates_presence_of :fname, :lname, :licnum, :dob

	belongs_to :truck

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/models/load.rb
class Load < ActiveRecord::Base
	validates_presence_of :length, :width, :height, :weight, :nickname, :shipper_id

	belongs_to :trailer
	belongs_to :shipper

end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
	validates_presence_of :name

	has_many :loads

end

app/models/testenv.rb
class Testenv < ActiveRecord::Base
end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
	validates_presence_of :licnum, :length, :width, :height

	belongs_to :truck
	has_many :loads

	def select_label
		if self.nickname != (nil or '')
			return "#{self.licnum} (#{self.nickname})"
		else
			return "#{self.licnum}"
		end
	end

end

app/models/truck.rb
class Truck < ActiveRecord::Base
	validates_presence_of :licnum

	has_many :drivers
	has_one :trailer
	accepts_nested_attributes_for :trailer

	def select_label
		if self.nickname != (nil or '')
			return "#{self.licnum} (#{self.nickname})"
		else
			return "#{self.licnum}"
		end
	end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]

  def get_item
    @driver = Driver.find(params[:id])
  end

  def index
    @title = 'All Drivers'
    @driver = Driver.all.order(:lname)
  end

  def show
    @driver = Driver.find(params[:id])
    @title = @driver.fname + ' ' + @driver.lname
    respond_to do |f|
      f.html
      f.json { render json: @driver}
    end
  end

  def edit
  	@title = 'Edit Driver'
  	session[:return_to] = request.referer
  end

  def new
  	@title = 'Create Driver'
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)

    if @driver.save
      redirect_to(drivers_path, notice: 'Driver was created successfully')
    else
      redirect_to(drivers_path, alert: 'Cannot create driver.')
    end
  end

  def update
  	@driver = Driver.update(@driver.id, driver_params)

    if @driver.save
    	redirect_to(session.delete(:return_to), notice: 'Driver was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(drivers_path, alert: 'Cannot update driver.')
    end
  end

  def destroy
    @driver.destroy
    redirect_to(drivers_path, notice: 'Driver was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def driver_params
    params.require(:driver).permit(:fname, :lname, :licnum, :dob, :truck_id)
  end

end

app/controllers/input_controller.rb
class InputController < ApplicationController
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]


  def get_item
    @load = Load.find(params[:id])
  end

  def index
    @title = 'All Loads'
    @load = Load.all.order(:nickname)
  end

  def show
    @load = Load.find(params[:id])
    @title = @load.nickname
    respond_to do |f|
      f.html
      f.json { render json: @load}
    end
  end

  def edit
    @title = "Edit Load"
    session[:return_to] = request.referer
  end

  def new
    @title = "New Load"
    @load = Load.new
  end

  def create
    @load = Load.new(load_params)

    if @load.save
      redirect_to(loads_path, notice: 'Load was created successfully')
    else
      redirect_to(loads_path, alert: 'Cannot create load.')
    end
  end

  def update
    @load = Load.update(@load.id, load_params)

    if @load.save
      redirect_to(session.delete(:return_to), notice: 'Load was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(loads_path, alert: 'Cannot update load.')
    end
  end

  def destroy
    @load.destroy
    redirect_to(loads_path, notice: 'Load was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def load_params
    params.require(:load).permit(:nickname, :length, :width, :height, :weight, :trailer_id, :shipper_id)
  end

end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController

  before_action :get_item, only: [:edit, :update, :destroy]

  def get_item
    @trailer = Trailer.find(params[:id])
  end

  def index
    @title = 'All Trailers'
    @trailer = Trailer.all.order(:licnum)
  end

  def show
    @trailer = Trailer.find(params[:id])
    if @trailer.nickname != (nil or '')
      @title = @trailer.licnum + ' (' + @trailer.nickname+')'
    else
      @title = @trailer.licnum
    end
    respond_to do |f|
      f.html
      f.json { render json: @trailer}
    end
  end

  def edit
    @title = "Edit Trailer"
    session[:return_to] = request.referer
  end

  def new
    @title = "New Trailer"
    @trailer = Trailer.new
  end

  def create
    @trailer = Trailer.new(trailer_params)
    truck = Truck.find(params[:trailer][:truck_id])
    truck.trailer = @trailer
    @trailer.truck = truck
    if @trailer.save
      redirect_to(trailers_path, notice: 'Trailer was created successfully')
    else
      redirect_to(trailers_path, alert: 'Cannot create trailer.')
    end
  end

  def update
    @trailer = Trailer.update(@trailer.id, trailer_params)

    truck = Truck.find(params[:trailer][:truck_id])
    truck.trailer = @trailer
    @trailer.truck = truck
    if @trailer.save
      redirect_to(session.delete(:return_to), notice: 'Trailer was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(trailers_path, alert: 'Cannot update trailer.')
    end
  end

  def destroy
    @trailer.destroy
    redirect_to(trailers_path, notice: 'Trailer was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def trailer_params
    params.require(:trailer).permit(:nickname, :licnum, :length, :width, :height, :truck_id)
  end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

	before_action :get_item, only: [:edit, :update, :destroy]

  def get_item
    @truck = Truck.find(params[:id])
  end

  def index
    @title = 'All Trucks'
    @truck = Truck.all.order(:nickname)
  end

  def show
    @truck = Truck.find(params[:id])
    if @truck.nickname != (nil or '')
      @title = @truck.licnum + ' (' + @truck.nickname+')'
    else
      @title = @truck.licnum
    end
    respond_to do |f|
      f.html
      f.json { render json: @truck}
    end
  end

  def edit
    @title = "Edit Truck"
    session[:return_to] = request.referer
  end

  def new
    @title = "New Truck"
    @truck = Truck.new
  end

  def create
    @truck = Truck.new(truck_params)
    trailer = Trailer.find(params[:truck][:trailer_id])
    @truck.trailer = trailer
    if @truck.save
      redirect_to(trucks_path, notice: 'Truck was created successfully')
    else
      redirect_to(trucks_path, alert: 'Cannot create truck.')
    end
  end

  def update
    @truck = Truck.update(@truck.id, truck_params)

    trailer = Trailer.find(params[:truck][:trailer_id])
    @truck.trailer = trailer
    if @truck.save
      redirect_to(session.delete(:return_to), notice: 'Truck was updated successfully')
      #redirect_to(drivers_path, 
    else
      redirect_to(trucks_path, alert: 'Cannot update truck.')
    end
  end

  def destroy
    @truck.destroy
    redirect_to(trucks_path, notice: 'Truck was deleted successfully')
  end

  

  private
  ## Strong Parameters 
  def truck_params
    params.require(:truck).permit(:nickname, :licnum, :trailer_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/helpers/load_helper.rb
module LoadHelper
end

app/helpers/shipper_helper.rb
module ShipperHelper
end

app/helpers/trailer_helper.rb
module TrailerHelper
end

app/helpers/truck_helper.rb
module TruckHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/trailers/edit.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @trailer do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :nickname, label: 'Nickname', placeholder: 'Optional'%>
	  	<%= f.input :length, label: 'Length' %>
	  	<%= f.input :width, label: 'Width' %>
	  	<%= f.input :height, label: 'Height' %> 
	  	<%= f.input :truck_id,:collection => Truck.all,:label_method => :select_label,:value_method => :id,:label => "Truck" %>
			<%#= f.association :drivers %>
			<%#= f.association :trailer %>

	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/trailers/index.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>
	<h2><%=@title%></h2>
		<table>
			<thead>
			<tr>
				
				<th>License #</th>
				<th>Nickname</th>
				<th>Dimensions (LxWxH)</th>
				<th>Truck</th>
				<th>Loads</th>
				<th>Modify</th>
			</tr>
			</thead>
			
			<tbody>
			<% @trailer.each do |c| %>
			
			<tr>
				<td><%= link_to c.licnum, c%></td>
				<td>
				<% if c.nickname != (nil or '') %>
						<%= c.nickname%>
				<%else%>
					<%= 'No Nickname' %>
				<%end%>
				</td>
				<td><%=c.length%> x <%=c.width%> x <%=c.height%></td>
				<td>
				<% if c.truck != nil %>
						<%if c.truck.nickname != (nil or '')%>
      				<%=link_to c.truck.licnum, truck_path(c.truck)%>  <%=' (' + c.truck.nickname+')'%>
    				<%else%>
      				<%=link_to c.truck.licnum, truck_path(c.truck)%>
    				<%end%>
				<%else%>
						<%= 'No Truck' %>
				<%end%>
				</td>
				<td>
				<% if c.loads != [] %>
						<% c.loads.each do |t|%>
								<%= link_to t.nickname, load_path(t)%><br />
						<%end%>
				<%else%>
						<%= 'No Loads' %>
				<%end%>
				</td>				
				<td>
						<%= link_to "Edit", edit_trailer_path(c), class: 'button small' %>
						<%= link_to "Delete", c, method: :delete, class: 'button small'  %>
				</td>
			</tr>
			
			<%end%>
			</tbody>
			

		</table>
		
		<% if @trailer.size == 0 %>
				<em>No Trailers Found</em><br /><br />
		<%end%>

		<a href="/trailers/new" class="button small">New Trailer</a>

	</div>

app/views/trailers/new.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

	<h2><%=@title%></h2>
	

	<div class = 'large-6 columns'>
	<%= simple_form_for @trailer do |f| %>
			<%= f.input :licnum, label: 'License #' %>
	  	<%= f.input :nickname, label: 'Nickname', placeholder: 'Optional'%>
	  	<%= f.input :length, label: 'Length' %>
	  	<%= f.input :width, label: 'Width' %>
	  	<%= f.input :height, label: 'Height' %>
	  	<%= f.input :truck_id,:collection => Truck.all,:label_method => :select_label,:value_method => :id,:label => "Truck" %>
			<%#= f.association :drivers %>
			<%#= f.association :trailer %>

	  	<%= f.button :submit, class: 'button small' %>
	<% end %>
	</div>

app/views/trailers/show.html.erb
<% content_for :title do %>
<%=@title%>
<% end %>

<h2><%=@title%></h2>

<table>
	<thead>
		<tr>
			<th>License #</th>
				<th>Nickname</th>
				<th>Dimensions (LxWxH)</th>
				<th>Truck</th>
				<th>Loads</th>
				
		</tr>
	</thead>
	
	<tbody>
		<tr>
		<td><%= @trailer.licnum%></td>
		<td>
			<% if @trailer.nickname != (nil or '') %>
					<%= @trailer.nickname%>
			<%else%>
				<%= 'No Nickname' %>
			<%end%>
		</td>
		<td><%=@trailer.length%> x <%=@trailer.width%> x <%=@trailer.height%></td>
		<td>
			<% if @trailer.truck != nil %>
						<%if @trailer.truck.nickname != (nil or '')%>
      				<%=link_to @trailer.truck.licnum, truck_path(@trailer.truck)%>  <%=' (' + @trailer.truck.nickname+')'%>
    				<%else%>
      				<%=link_to @trailer.truck.licnum, truck_path(@trailer.truck)%>
    				<%end%>
				<%else%>
						<%= 'No Truck' %>
				<%end%>
		</td>
		<td>
		<% if @trailer.loads != [] %>
						<% @trailer.loads.each do |t|%>
								<%= link_to t.nickname, load_path(t)%><br />
						<%end%>
				<%else%>
						<%= 'No Loads' %>
				<%end%>
		</td>
		</tr>	
	</tbody>
	


</table>
<%= link_to "Edit Trailer", edit_trailer_path(@trailer), class: 'button small' %>
<a href="/trailers" class="button small">All Trailers</a>